site_name: Marsheol de 笔记本
dev_addr: '127.0.0.1:8090'

# Configuration
theme:
  name: null
  custom_dir: material

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: black
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/icons/favicon.ico
  logo:
    icon: "\uE80C"


nav:
  - 首页: index.md
  - 笔记: 
    - MySQL: mysql.md
    - Linux: linux.md